---
# tasks file for apache2
- name: install apache2
  apt: name=apache2 state=present
- name: copy configuration
  copy: src=apache2.conf dest=/etc/apache2
  notify:
    - restart apache2 service
- name: start apache2
  service: name=apache2 state=started
- name: copy index.html 
  copy: src=index.html dest=/var/www/html/index.html
